### ISSUE TITLE
Module doesn't respect environment variables

### ISSUE THREAD

**Issue by JordanForeman** [JordanForeman/cf-find#13]
Without explicitly passing in `env.AWS_ACCESS_KEY_ID` and `env.AWS_SECRET_ACCESS_KEY`, this module expects `~/.aws/credentials` to be populated. It'd be nifty if the `aws-sdk` actually did this itself, but 🤷‍♂ 

```bash
(node:5327) UnhandledPromiseRejectionWarning: CredentialsError: Missing credentials in config
    at IncomingMessage.<anonymous> (/home/runner/work/<project>/<project>/node_modules/aws-sdk/lib/util.js:895:34)
    at IncomingMessage.emit (events.js:214:15)
    at IncomingMessage.EventEmitter.emit (domain.js:476:20)
    at endReadableNT (_stream_readable.js:1178:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**Comment by JordanForeman** [comment]
🤦‍♂ this was a mistake on my part...I had mistyped my secrets configuration in my Github actions workflow document.
